### ISSUE TITLE
Can't sign in: Invalid request: only one authentication method is allowed

### ISSUE THREAD

**Issue by emepetres** [FIWARE-TMForum/Business-API-Ecosystem#16]
During the sign-in process, after authorising my user in the IDM, the proxy fails to finish properly with the exception below.

I'm using docker compose, v6.4.0 version of the proxy. IDM is version 7.0.0

```
biz         | FATAL: Server - a206762f-3016-481a-b231-c75155dda968 - ::ffff:10.38.0.1 - Anonymous - GET: /auth/fiware/callback?code=0c7ab0efe58c911bc17a3dd8e19a37b4a59b2c9c&state=eyJjYW1lX2Zyb21fcGF0aCI6Ii8ifQ - Unexpected unhandled exception - InternalOAuthError: failed to fetch user profile. Stack trace:
biz         | InternalOAuthError: failed to fetch user profile (status: 400 data: {"statusCode":400,"status":400,"code":400,"message":"Invalid request: only one authentication method is allowed","name":"invalid_request"})
biz         |     at /business-ecosystem-logic-proxy/node_modules/passport-fiware-oauth/lib/passport-fiware-oauth/oauth2.js:89:19
biz         |     at passBackControl (/business-ecosystem-logic-proxy/node_modules/oauth/lib/oauth2.js:132:9)
biz         |     at IncomingMessage.<anonymous> (/business-ecosystem-logic-proxy/node_modules/oauth/lib/oauth2.js:157:7)
biz         |     at emitNone (events.js:91:20)
biz         |     at IncomingMessage.emit (events.js:185:7)
biz         |     at endReadableNT (_stream_readable.js:974:12)
biz         |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
biz         |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

**Comment by fdelavega** [comment]
Hi,

This is a know issue with keyrock v7 since the method for retrieving user info has changed a bit, we are working for updating the pasport-auth library so we can handle the usage of the v7

**Comment by emepetres** [comment]
Hi @fdelavega ,

I need to have the new biz with the new idm working as soon as possible. Is there any workaround in the develop branch or other place that I can try to have it working locally until the issue is properly fixed?

**Comment by fdelavega** [comment]
Hi,

The develop docker images are supporting the new keyrock version, try to change all the tags in the docker-compose by develop.

Let me know if you face issues

**Comment by emepetres** [comment]
Thanks, I saw the commit. It is working now!

**Comment by Urtza2** [comment]
Hi @fdelavega,
I have the same problem as emetrepes.
```
FATAL: Server - 04a4d6fc-f264-4887-a29a-b384191d1f78 - ::1 - Anonymous - GET: /auth/fiware/callback?code=a76b0fafeaaf7b7578f1bd45e973502fb1bf8269&state=eyJjYW1lX2Zyb21fcGF0aCI6Ii8ifQ - Unexpected unhandled exception - InternalOAuthError: failed to fetch user profile. Stack trace:
InternalOAuthError: failed to fetch user profile (status: 400 data: "Invalid request: only one authentication method is allowed")
    at /home/user1/Business-API-Ecosystem/business-ecosystem-logic-proxy/node_modules/passport-fiware-oauth/lib/passport-fiware-oauth/oauth2.js:106:19
    at passBackControl (/home/user1/Business-API-Ecosystem/business-ecosystem-logic-proxy/node_modules/oauth/lib/oauth2.js:139:9)
    at IncomingMessage.<anonymous> (/home/user1/Business-API-Ecosystem/business-ecosystem-logic-proxy/node_modules/oauth/lib/oauth2.js:164:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

I have install KeyRock using git clone and the version that I have is: 

```
{
	"keyrock": {
		"version": "7.0.1",
		"release_date": "2018-06-25",
		"uptime": "",
		"git_hash": "https://github.com/ging/fiware-idm/releases/tag/7.0.1",
		"doc": "https://fiware-idm.readthedocs.io/en/7.0.1/",
		"api": {
			"version": "v1",
			"link": ""
		}
	}
}
```
Do you know how can I solve my problem?

Thanks
Urtza

**Comment by Urtza2** [comment]
I have downloaded Biz-Ecosystem from git and installed using script.
git clone https://github.com/FIWARE-TMForum/Business-API-Ecosystem.git
