### ISSUE TITLE
Can't create a catalogue

### ISSUE THREAD

**Issue by emepetres** [FIWARE-TMForum/Business-API-Ecosystem#18]
I'm having the following error when creating a new catalogue (when clicking on the finish button):

```
2018-05-14 11:34:15.343  - FATAL: Server - a10cd6fe-d35e-45d3-9d1c-b3b9166ee17a - ::ffff:62.14.219.15 - f8297ebc-4a60-4a43-9d74-cec472bbc01f - POST: /DSProductCatalog/api/catalogManagement/v2/catalog - Unexpected unhandled exception - TypeError: Cannot read property 'enabled' of undefined. Stack trace:
TypeError: Cannot read property 'enabled' of undefined
    at Object.exports.getIndividualURL (/business-ecosystem-logic-proxy/lib/tmfUtils.js:225:21)
    at /business-ecosystem-logic-proxy/lib/tmfUtils.js:191:43
    at Array.some (native)
    at Object.exports.hasPartyRole (/business-ecosystem-logic-proxy/lib/tmfUtils.js:189:42)
    at Object.exports.isOwner (/business-ecosystem-logic-proxy/lib/tmfUtils.js:32:47)
    at createHandler (/business-ecosystem-logic-proxy/controllers/tmf-apis/catalog.js:729:22)
    at /business-ecosystem-logic-proxy/controllers/tmf-apis/catalog.js:818:25
    at /business-ecosystem-logic-proxy/controllers/tmf-apis/catalog.js:704:21
    at Request._callback (/business-ecosystem-logic-proxy/controllers/tmf-apis/catalog.js:71:17)
    at Request.self.callback (/business-ecosystem-logic-proxy/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/business-ecosystem-logic-proxy/node_modules/request/request.js:1163:10)
2018-05-14 11:34:15.353  - WARN: Server - a10cd6fe-d35e-45d3-9d1c-b3b9166ee17a - ::ffff:62.14.219.15 - f8297ebc-4a60-4a43-9d74-cec472bbc01f - POST: /DSProductCatalog/api/catalogManagement/v2/catalog - Status: 500
```

**Comment by emepetres** [comment]
Using the docker compose files of develop branch, I'm getting a different error when creating a catalogue or product: **The user making the request and the specified owner are not the same user**

Creating catalogue error:
```
proxy_1     | 2018-05-15 15:56:31.621  - WARN: TMF - b15d6f92-bbb8-4186-b46e-18f395796229 - ::ffff:10.38.0.1 - f8297ebc-4a60-4a43-9d74-cec472bbc01f - POST: /DSProductCatalog/api/catalogManagement/v2/catalog - Pre-Validation (DSProductCatalog): The user making the request and the specified owner are not the same user
proxy_1     | 2018-05-15 15:56:31.652  - WARN: Server - b15d6f92-bbb8-4186-b46e-18f395796229 - ::ffff:10.38.0.1 - f8297ebc-4a60-4a43-9d74-cec472bbc01f - POST: /DSProductCatalog/api/catalogManagement/v2/catalog - Status: 403
```
Creating Product error:
```
proxy_1     | 2018-05-15 15:59:45.856  - WARN: TMF - 315bf074-3620-47d7-89c2-4fc836eb37ea - ::ffff:10.38.0.1 - f8297ebc-4a60-4a43-9d74-cec472bbc01f - POST: /DSProductCatalog/api/catalogManagement/v2/productSpecification - Pre-Validation (DSProductCatalog): The user making the request and the specified owner are not the same user
proxy_1     | 2018-05-15 15:59:45.862  - WARN: Server - 315bf074-3620-47d7-89c2-4fc836eb37ea - ::ffff:10.38.0.1 - f8297ebc-4a60-4a43-9d74-cec472bbc01f - POST: /DSProductCatalog/api/catalogManagement/v2/productSpecification - Status: 403
```

**Comment by fdelavega** [comment]
Both errors are due to the same issue.

There is a problem with the software provided by the TMForum for managing the catalog, basically when it generates hrefs of objects it uses the host header without taking into account X-Forwarded-for headers or similar, so the Href of the user object generated by the API is different from the one included in the relatedParty object (the host and port basically). This causes the second error

To overcome this issues in the develop branch we have included some configuration params, first of all in the proxy, we have included a new setting  that enables to specify whether the BAE is going to be accessed from a URL which is not the same as the one where it is running (e.g when using apache for SSL management). This is generating the second error.

Is this one: the host and port should be the ones used by external users to access the system and secured specified whether the system is accessed using SSL.

```
config.proxy = {
    enabled: true,
    host: 'proxy.docker',
    secured: false,
    port: 8004
};
```

In the same way there have been included a `settings.properties` file, where you can specify which is the URL that should be used to generate API HREFs, in docker is included in apis-conf folder and in a source installation is should be included in `/etc/default/tmf/`

Once you provided this configuration both errors should dissapear
