### ISSUE TITLE
Apps arent loaded yet

### ISSUE THREAD

**Issue by fermenreq** [FIWARE-TMForum/Business-API-Ecosystem#6]
Hi, 
I following up the installation guide, using both installation scripts and finally I get an error when I exectute : 

`root@ge2:/home/FIWARE/Business-API-Ecosystem/business-ecosystem-charging-backend/src# ./manage.py crontab add`

`
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/FIWARE/Business-API-Ecosystem/business-ecosystem-charging-backend/src/settings.py", line 155, in <module>
    from django.contrib.sites import models as site_app
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sites/models.py", line 84, in <module>
    class Site(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
` 

Machine details: 

`root@ge2:/home/FIWARE/Business-API-Ecosystem/business-ecosystem-charging-backend/src# uname -a
Linux ge2.cloudlab.atos.net 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`

Thanks in advance

**Comment by fdelavega** [comment]
Hi,
Please try to update the software to the last version, that error is due to having the sites framework included in settings.py while it is not anymore used in the software

**Comment by fdelavega** [comment]
I am closing this issue, please reopen if the problem persists
